/* =====================================================
    BUSINESS QUESTION:
    What is the average customer lifetime value (CLV) by campaign?

    METRICS:
    - Retention Rate
    - ARPU (Average Revenue Per User)
    - SLV (Sum of Lifetime Value)
    - CLV (Customer Lifetime Value)

    OUTPUT:
    First_Order_YearMonth | Campaign | AVG_CLV_ByCampaign | Rank
===================================================== */

WITH CTE_OVERALL AS (
    SELECT S.ORDER_ID, S.CUSTOMER_ID, S.PRODUCT_ID, S.CHANNEL, S.CHANNEL_MARKETING, M.CHANNEL AS CHANNEL_FACTMARKETING, S.REGION, S.ORDER_DATE, S.REVENUE, S.COGS, 
        S.DISCOUNT_AMOUNT, S.[STATUS], C.CAMPAIGN_ID, M.CLICKS, M.IMPRESSION, M.VISIT, M.SPEND, C.CAMPAIGN_NAME, C.OBJECTIVE
    FROM fact_sales S
        INNER JOIN fact_marketing M ON M.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10)) AND S.CHANNEL_MARKETING = M.CHANNEL
        INNER JOIN dim_campaign C ON C.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10))
)
, CTE_FIRSTORDERDATE AS (
    SELECT CUSTOMER_ID,
            MIN(ORDER_DATE) AS FIRST_ORDERDATE
        FROM CTE_OVERALL
        GROUP BY CUSTOMER_ID
)
, CTE_FIRSTCAMPAIGN AS (
    SELECT O.CUSTOMER_ID, 
            MIN(F.FIRST_ORDERDATE) AS FIRST_ORDERDATE, 
            MIN(O.CAMPAIGN_ID) AS CAMPAIGN_ID
        FROM CTE_FIRSTORDERDATE F
            INNER JOIN CTE_OVERALL O
                ON F.CUSTOMER_ID = O.CUSTOMER_ID
                AND F.FIRST_ORDERDATE = O.ORDER_DATE
        GROUP BY O.CUSTOMER_ID
)
, CTE_COHORT AS (
    SELECT O.CUSTOMER_ID, O.ORDER_DATE, F.FIRST_ORDERDATE, FC.CAMPAIGN_ID, REVENUE,
            YEAR(F.FIRST_ORDERDATE) * 100 + MONTH(F.FIRST_ORDERDATE) AS FIRST_ORDERDATE_YEARMONTH,
            DATEDIFF(MONTH,F.FIRST_ORDERDATE,O.ORDER_DATE) AS COHORT
        FROM CTE_OVERALL O
            INNER JOIN CTE_FIRSTORDERDATE F ON O.CUSTOMER_ID = F.CUSTOMER_ID
            INNER JOIN CTE_FIRSTCAMPAIGN FC ON FC.CUSTOMER_ID = O.CUSTOMER_ID
)
, CTE_NEWCUSTOMERS AS (
    SELECT FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID,
            COUNT(DISTINCT CUSTOMER_ID) AS NEW_CUSTOMERS
        FROM CTE_COHORT
        GROUP BY FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID
)
, CTE_RETENTION AS (
    SELECT C.FIRST_ORDERDATE_YEARMONTH, C.CAMPAIGN_ID,C.COHORT,N.NEW_CUSTOMERS,
            CAST((COUNT(DISTINCT CUSTOMER_ID) *100 / N.NEW_CUSTOMERS) AS decimal(10,2)) AS RETENTION_RATE
        FROM CTE_COHORT C
            INNER JOIN CTE_NEWCUSTOMERS N 
                ON C.FIRST_ORDERDATE_YEARMONTH = N.FIRST_ORDERDATE_YEARMONTH
                AND C.CAMPAIGN_ID = N.CAMPAIGN_ID
        GROUP BY C.FIRST_ORDERDATE_YEARMONTH, C.CAMPAIGN_ID,C.COHORT, N.NEW_CUSTOMERS
)
, CTE_SLV AS (
    SELECT FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID,
            SUM(RETENTION_RATE) / 100 AS SLV
        FROM CTE_RETENTION
        GROUP BY FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID
)
, CTE_ARPU AS (
    SELECT FIRST_ORDERDATE_YEARMONTH, C.CAMPAIGN_ID,
            SUM(REVENUE) / COUNT(DISTINCT CUSTOMER_ID) AS ARPU
        FROM CTE_COHORT C 
        GROUP BY FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID
)
, CTE_CLV AS (
    SELECT S.FIRST_ORDERDATE_YEARMONTH, S.CAMPAIGN_ID,
            CAST((SLV * ARPU) AS decimal(20,2)) AS AVG_CLV_ByCampaign
        FROM CTE_ARPU A 
            INNER JOIN CTE_SLV S 
                ON S.CAMPAIGN_ID = A.CAMPAIGN_ID
                AND S.FIRST_ORDERDATE_YEARMONTH = A.FIRST_ORDERDATE_YEARMONTH
)
SELECT FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID, AVG_CLV_ByCampaign,
        RANK() OVER(ORDER BY AVG_CLV_ByCampaign DESC) AS R
FROM CTE_CLV
