/* =====================================================
    BUSINESS QUESTION:
    What is the customer retention rate by cohort and campaign?

    METRICS:
    - New Customers
    - Retention Rate
    - Cohort (Months since first order)

    OUTPUT:
    First_Order_YearMonth | Campaign | Cohort | New_Customers | Retention_Rate
===================================================== */

WITH CTE_OVERALL AS (
    SELECT S.ORDER_ID, S.CUSTOMER_ID, S.PRODUCT_ID, S.CHANNEL, S.CHANNEL_MARKETING, M.CHANNEL AS CHANNEL_FACTMARKETING, S.REGION, S.ORDER_DATE, S.REVENUE, S.COGS, 
        S.DISCOUNT_AMOUNT, S.[STATUS], C.CAMPAIGN_ID, M.CLICKS, M.IMPRESSION, M.VISIT, M.SPEND, C.CAMPAIGN_NAME, C.OBJECTIVE
    FROM fact_sales S
        INNER JOIN fact_marketing M ON M.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10)) AND S.CHANNEL_MARKETING = M.CHANNEL
        INNER JOIN dim_campaign C ON C.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10))
)
, CTE_FIRSTORDERDATE AS (
    SELECT CUSTOMER_ID,
            MIN(ORDER_DATE) AS FIRST_ORDERDATE
        FROM CTE_OVERALL
        GROUP BY CUSTOMER_ID
)
, CTE_FIRSTCAMPAIGN AS (
    SELECT O.CUSTOMER_ID, 
            MIN(F.FIRST_ORDERDATE) AS FIRST_ORDERDATE, 
            MIN(O.CAMPAIGN_ID) AS CAMPAIGN_ID
        FROM CTE_FIRSTORDERDATE F
            INNER JOIN CTE_OVERALL O
                ON F.CUSTOMER_ID = O.CUSTOMER_ID
                AND F.FIRST_ORDERDATE = O.ORDER_DATE
        GROUP BY O.CUSTOMER_ID
)
, CTE_COHORT AS (
    SELECT O.CUSTOMER_ID, O.ORDER_DATE, F.FIRST_ORDERDATE, FC.CAMPAIGN_ID, REVENUE,
            YEAR(F.FIRST_ORDERDATE) * 100 + MONTH(F.FIRST_ORDERDATE) AS FIRST_ORDERDATE_YEARMONTH,
            DATEDIFF(MONTH,F.FIRST_ORDERDATE,O.ORDER_DATE) AS COHORT
        FROM CTE_OVERALL O
            INNER JOIN CTE_FIRSTORDERDATE F ON O.CUSTOMER_ID = F.CUSTOMER_ID
            INNER JOIN CTE_FIRSTCAMPAIGN FC ON FC.CUSTOMER_ID = O.CUSTOMER_ID
)
, CTE_NEWCUSTOMERS AS (
    SELECT FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID,
            COUNT(DISTINCT CUSTOMER_ID) AS NEW_CUSTOMERS
        FROM CTE_COHORT
        GROUP BY FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID
)
, CTE_RETENTION AS (
    SELECT C.FIRST_ORDERDATE_YEARMONTH, C.CAMPAIGN_ID,C.COHORT,N.NEW_CUSTOMERS,
            CAST((COUNT(DISTINCT CUSTOMER_ID) *100 / N.NEW_CUSTOMERS) AS decimal(10,2)) AS RETENTION_RATE
        FROM CTE_COHORT C
            INNER JOIN CTE_NEWCUSTOMERS N 
                ON C.FIRST_ORDERDATE_YEARMONTH = N.FIRST_ORDERDATE_YEARMONTH
                AND C.CAMPAIGN_ID = N.CAMPAIGN_ID
        GROUP BY C.FIRST_ORDERDATE_YEARMONTH, C.CAMPAIGN_ID,C.COHORT, N.NEW_CUSTOMERS
)
SELECT *
FROM CTE_RETENTION
